export const petsMasterData = {
  pets: [
    {
      species: "Dog",
      breeds: [
        "Labrador Retriever",
        "German Shepherd",
        "Golden Retriever",
        "Pomeranian",
        "Beagle",
        "Bulldog",
        "Pug",
        "Rottweiler",
        "Dachshund",
        "Siberian Husky",
      ],
    },
    {
      species: "Cat",
      breeds: [
        "Persian",
        "Siamese",
        "Maine Coon",
        "Bengal",
        "British Shorthair",
        "Ragdoll",
        "Sphynx",
        "Abyssinian",
        "Scottish Fold",
        "Russian Blue",
      ],
    },
    {
      species: "Bird",
      breeds: [
        "Parakeet",
        "Cockatiel",
        "Lovebird",
        "Canary",
        "Macaw",
        "African Grey",
        "Finch",
        "Budgerigar",
        "Conure",
        "Cockatoo",
      ],
    },
    {
      species: "Rabbit",
      breeds: [
        "Holland Lop",
        "Netherland Dwarf",
        "Lionhead",
        "Flemish Giant",
        "Mini Rex",
        "English Angora",
        "French Lop",
        "Harlequin",
        "Californian",
        "Chinchilla Rabbit",
      ],
    },
    {
      species: "Fish",
      breeds: [
        "Goldfish",
        "Betta",
        "Guppy",
        "Angelfish",
        "Molly",
        "Platy",
        "Koi",
        "Oscar",
        "Tetra",
        "Discus",
      ],
    },
    {
      species: "Cow",
      breeds: [
        "Gir",
        "Sahiwal",
        "Red Sindhi",
        "Tharparkar",
        "Ongole",
        "Kankrej",
        "Hallikar",
        "Deoni",
        "Jersey",
        "Holstein Friesian",
      ],
    },
  ],
};
